#To check all the error 
import sys

randomList = ['a', 0, 2]

for entry in randomList:
    try:
        print("The entry is", entry)
        r = 1/int(entry)
        break
    except:
        print("Oops!", sys.exc_info()[0], "occurred.")
        print("Next entry.")
        print()
print("The reciprocal of", entry, "is", r)
#TobDesign a simple calculator app with try and except for all use cases

print("* MY CALCULATOR*\n")
print("Math Operations")
print("       +\n" "       -\n" "       *\n" "       /\n")
 
num1 = float(input("Enter First Number: "))
op = input("Enter Operation: ")
num2 = float(input("Enter Second Number: "))
 
try:
    val = int(num1)
except ValueError:
    print("Error: Enter A Valid Number")
 
try:
    val = int(num2)
except ValueError:
    print("Error: Enter A Valid Number")
 
if op == "+":
    print(num1 + num2)
elif op == "-":
    print(num1 - num2)
elif op == "*":
    print(num1 * num2)
elif op == "/":
    print(num1 / num2)
else:
    print("Not a valid math problem")
    
try: 

    amount =3999

    if amount < 2999:
    	raise ValueError("please add money in your account") 

    else: 
     print("You are eligible to purchase course") 
except ValueError as e: 
     print(e) 
     #To get an input inside the try catch block
try:
    age=int(input('Enter your age: '))
except:
    print ('You have entered an invalid value.')
